apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  selector:
    matchLabels:
      app: blue-green-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: blue-green-deployment
        version: blue
    spec:
      containers:
      - name: blue-deployment
        image: totinbolo45/blue:v1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
spec:
  selector:
    matchLabels:
      app: blue-green-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: blue-green-deployment
        version: green
    spec:
      containers:
      - name: green-deployment
        image: totinbolo45/green:v1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  selector:
    app: blue-green-deployment
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort